<?php /** @var array $_ */ ?>
<div id="stickynotes-app" data-version="<?php p($_['version']); ?>">
    <div id="sn-error" class="sn-error" hidden></div>
    <div class="sn-toolbar">
        <div><div class="sn-title-row"><h2><?php p($l->t('Sticky Notes')); ?></h2><span class="sn-version">v<?php p($_['version']); ?></span></div>
        <div id="sn-stats" class="sn-stats"><span>🗒 <strong id="sn-stat-total">0</strong> <?php p($l->t('Total')); ?></span><span>● <strong id="sn-stat-active">0</strong> <?php p($l->t('Active')); ?></span><span>✓ <strong id="sn-stat-done">0</strong> <?php p($l->t('Completed')); ?></span></div></div>
        <div class="sn-toolbar-actions">
            <button id="sn-style-settings" type="button" class="sn-icon-button" title="<?php p($l->t('Sticky note styles and categories')); ?>">🎨</button>
            <button id="sn-new" type="button" class="primary"><?php p($l->t('New sticky note')); ?></button>
            <button id="sn-settings" type="button" class="sn-icon-button" title="<?php p($l->t('Application settings')); ?>">⚙</button>
        </div>
    </div>
    <div id="sn-category-filters" class="sn-category-filters"></div>
    <div class="sn-filters"><button type="button" data-filter="all" class="active"><?php p($l->t('All')); ?></button><button type="button" data-filter="mine"><?php p($l->t('My notes')); ?></button><button type="button" data-filter="assigned"><?php p($l->t('Assigned to me')); ?></button><button type="button" data-filter="shared"><?php p($l->t('Shared')); ?></button><button type="button" data-filter="done"><?php p($l->t('Done')); ?></button>
    <select id="sn-sort" class="sn-sort"><option value="manual"><?php p($l->t('Manual order')); ?></option><option value="category"><?php p($l->t('By category')); ?></option><option value="newest"><?php p($l->t('Newest first')); ?></option><option value="oldest"><?php p($l->t('Oldest first')); ?></option></select>
    <select id="sn-page-size" class="sn-page-size"><option value="12">12</option><option value="24">24</option><option value="36">36</option><option value="48">48</option><option value="72">72</option></select><input id="sn-search" type="search" placeholder="<?php p($l->t('Search notes…')); ?>"></div>
    <div id="sn-board" class="sn-board"></div><div id="sn-empty" class="sn-empty" hidden><?php p($l->t('No sticky notes yet.')); ?></div>
    <div id="sn-pagination" class="sn-pagination" hidden><button id="sn-page-first" type="button">«</button><button id="sn-page-prev" type="button">‹</button><span id="sn-page-info"></span><button id="sn-page-next" type="button">›</button><button id="sn-page-last" type="button">»</button></div>
</div>

<div id="sn-note-overlay" class="sn-overlay" hidden aria-hidden="true"><div class="sn-modal sn-note-modal" role="dialog" aria-modal="true">
<div class="sn-dialog-title"><strong><?php p($l->t('Sticky note')); ?></strong><button id="sn-note-x" type="button" class="sn-dialog-close">×</button></div>
<div class="sn-rich-toolbar" role="toolbar"><button type="button" data-cmd="undo" title="<?php p($l->t('Undo')); ?>">↶</button><button type="button" data-cmd="redo" title="<?php p($l->t('Redo')); ?>">↷</button><select id="sn-block-format"><option value="p"><?php p($l->t('Normal text')); ?></option><option value="h1">H1</option><option value="h2">H2</option><option value="h3">H3</option><option value="blockquote"><?php p($l->t('Quote')); ?></option><option value="pre"><?php p($l->t('Code')); ?></option></select><button type="button" data-cmd="bold" title="Tučné"><strong>B</strong></button><button type="button" data-cmd="italic" title="Kurzíva"><em>I</em></button><button type="button" data-cmd="underline" title="Podtržení"><u>U</u></button><button type="button" data-cmd="strikeThrough" title="Přeškrtnutí"><s>S</s></button><button type="button" data-cmd="justifyLeft" title="Zarovnat vlevo">≡</button><button type="button" data-cmd="justifyCenter" title="Zarovnat na střed">≣</button><button type="button" data-cmd="justifyRight" title="Zarovnat vpravo">≡</button><button type="button" data-cmd="insertUnorderedList" title="Odrážkový seznam">• ≡</button><button type="button" data-cmd="insertOrderedList" title="Číslovaný seznam">1. ≡</button><button id="sn-insert-link" type="button" title="Vložit odkaz">🔗</button><button id="sn-remove-link" type="button" title="Odstranit odkaz">⛓</button><button id="sn-insert-table" type="button" title="Vložit tabulku">▦</button><button id="sn-insert-check" type="button" title="Zaškrtávací položka">☐</button><button id="sn-insert-emoji" type="button" title="Vložit emoji">☺</button></div>
<div id="sn-note-paper" class="sn-note-paper"><div id="sn-rich-title" class="sn-rich-title" contenteditable="true" data-placeholder="<?php p($l->t('Title')); ?>"></div><div class="sn-title-separator"></div><div id="sn-rich-body" class="sn-rich-body" contenteditable="true" data-placeholder="<?php p($l->t('Write a note…')); ?>"></div><input id="sn-id" type="hidden"><input id="sn-title" type="hidden"><textarea id="sn-content" hidden></textarea></div>
<div class="sn-editor-options"><div class="sn-row"><label><?php p($l->t('Category')); ?><select id="sn-category"></select></label><label><?php p($l->t('Marker color')); ?><input id="sn-color" type="color" value="#4f86f7"></label><label><?php p($l->t('Type')); ?><select id="sn-type"><option value="note"><?php p($l->t('Note')); ?></option><option value="task"><?php p($l->t('Task')); ?></option></select></label><label><?php p($l->t('Priority')); ?><select id="sn-priority"><option value="normal"><?php p($l->t('Normal')); ?></option><option value="important"><?php p($l->t('Important')); ?></option></select></label></div>
<div class="sn-row"><label class="sn-assignee-label"><?php p($l->t('Assign to')); ?><div class="sn-assignee-picker"><input id="sn-assigned-search" type="search" autocomplete="off" data-lpignore="true" placeholder="<?php p($l->t('Choose user or group')); ?>"><input id="sn-assigned" type="hidden"><div id="sn-assigned-results" class="sn-picker-results" hidden></div><div id="sn-assigned-selected" class="sn-assigned-selected" hidden></div></div></label><label><?php p($l->t('Due date')); ?><input id="sn-due" type="datetime-local"></label></div></div>
<div class="sn-dialog-actions"><button id="sn-note-cancel" type="button"><?php p($l->t('Cancel')); ?></button><button id="sn-save" type="button" class="primary"><?php p($l->t('Save')); ?></button></div></div></div>

<div id="sn-share-overlay" class="sn-overlay" hidden aria-hidden="true"><div class="sn-modal" role="dialog"><div class="sn-dialog-title"><strong><?php p($l->t('Share sticky note')); ?></strong><button id="sn-share-x" type="button">×</button></div><label><?php p($l->t('User or group')); ?><input id="sn-share-search"></label><div id="sn-share-results"></div><label><?php p($l->t('Permission')); ?><select id="sn-share-permission"><option value="view"><?php p($l->t('View only')); ?></option><option value="edit"><?php p($l->t('Can edit')); ?></option></select></label><div id="sn-current-shares"></div><div class="sn-dialog-actions"><button id="sn-share-close" type="button"><?php p($l->t('Close')); ?></button></div></div></div>

<div id="sn-settings-overlay" class="sn-overlay" hidden aria-hidden="true"><div class="sn-modal sn-settings-panel" role="dialog"><div class="sn-dialog-title"><strong>⚙ <?php p($l->t('Application settings')); ?></strong><button id="sn-settings-x" type="button">×</button></div><div class="sn-help-toggle"><label><input id="sn-help-mode" type="checkbox"> <?php p($l->t('Show detailed help')); ?></label></div>
<section class="sn-settings-section"><h3><?php p($l->t('Widget settings')); ?></h3><div class="sn-settings-grid"><label><?php p($l->t('Widget columns')); ?><select id="sn-widget-columns"><option>1</option><option>2</option><option>3</option><option>4</option></select><small class="sn-help"><?php p($l->t('Number of notes side by side in the Dashboard widget.')); ?></small></label><label><?php p($l->t('Widget rows')); ?><select id="sn-widget-rows"><option>1</option><option>2</option><option>3</option><option>4</option><option>5</option><option>6</option></select><small class="sn-help"><?php p($l->t('Maximum number of note rows in the Dashboard widget.')); ?></small></label></div></section>
<section class="sn-settings-section"><h3><?php p($l->t('Application layout')); ?></h3><div class="sn-settings-grid"><label><?php p($l->t('Notes per page')); ?><select id="sn-settings-page-size"><option>12</option><option>24</option><option>36</option><option>48</option><option>72</option></select><small class="sn-help"><?php p($l->t('Controls pagination on the main page.')); ?></small></label><label><?php p($l->t('Page width')); ?><select id="sn-layout-width"><option value="full"><?php p($l->t('Full width')); ?></option><option value="centered"><?php p($l->t('Centered')); ?></option></select><small class="sn-help"><?php p($l->t('Choose full-width or centered note board.')); ?></small></label><label class="sn-check-setting"><input id="sn-random-tilt" type="checkbox"> <?php p($l->t('Natural random tilt')); ?><small class="sn-help"><?php p($l->t('Notes keep a small stable random rotation.')); ?></small></label><label class="sn-check-setting"><input id="sn-note-shadow" type="checkbox"> <?php p($l->t('Sticky note shadow')); ?><small class="sn-help"><?php p($l->t('Adds a subtle paper shadow.')); ?></small></label></div></section>
<section class="sn-settings-section"><h3><?php p($l->t('Assignment notifications')); ?></h3><label><?php p($l->t('Send notifications')); ?><select id="sn-notification-mode"><option value="all"><?php p($l->t('Users and groups')); ?></option><option value="individual"><?php p($l->t('Individual users only')); ?></option><option value="group"><?php p($l->t('Groups only')); ?></option><option value="none"><?php p($l->t('No notifications')); ?></option></select><small class="sn-help"><?php p($l->t('Choose who receives assignment notifications.')); ?></small></label></section>
<div hidden><input id="sn-base-color" type="color" value="#fff59d"><select id="sn-marker-mode"><option value="header">header</option></select><input id="sn-marker-size" type="range" value="7"><div id="sn-style-preview"></div></div><div class="sn-dialog-actions"><button id="sn-settings-close" type="button"><?php p($l->t('Close')); ?></button><button id="sn-save-settings" type="button" class="primary"><?php p($l->t('Save settings')); ?></button></div></div></div>

<div id="sn-style-overlay" class="sn-overlay" hidden aria-hidden="true"><div class="sn-modal sn-style-panel" role="dialog"><div class="sn-dialog-title"><strong>🎨 <?php p($l->t('Sticky note styles and categories')); ?></strong><button id="sn-style-x" type="button">×</button></div><div class="sn-section-head"><div><h3><?php p($l->t('Categories and styles')); ?></h3><p class="sn-section-description"><?php p($l->t('A category is also a visual template for its notes.')); ?></p></div><button id="sn-add-category" type="button"><?php p($l->t('New category')); ?></button></div>
<div id="sn-category-editor" class="sn-category-editor" hidden><input id="sn-cat-id" type="hidden"><div class="sn-category-editor-surface"><div class="sn-category-fields"><label><?php p($l->t('Name')); ?><input id="sn-cat-name"></label><label><?php p($l->t('Category color')); ?><input id="sn-cat-color" type="color" value="#4f86f7"></label><label><?php p($l->t('Icon')); ?><input id="sn-cat-icon" type="hidden" value="📝"><button id="sn-icon-current" type="button">📝</button></label><label><?php p($l->t('Marker type')); ?><select id="sn-cat-marker-mode"><option value="inherit"><?php p($l->t('Use global setting')); ?></option><option value="header"><?php p($l->t('Colored header')); ?></option><option value="left"><?php p($l->t('Left stripe')); ?></option><option value="right"><?php p($l->t('Right stripe')); ?></option><option value="top"><?php p($l->t('Top stripe')); ?></option><option value="bottom"><?php p($l->t('Bottom stripe')); ?></option><option value="border"><?php p($l->t('Colored border')); ?></option><option value="corner"><?php p($l->t('Colored corner')); ?></option><option value="badge"><?php p($l->t('Colored badge')); ?></option><option value="full"><?php p($l->t('Whole note')); ?></option></select></label><label><?php p($l->t('Note background')); ?><input id="sn-cat-background" type="color" value="#fff59d"></label><label><?php p($l->t('Marker color')); ?><input id="sn-cat-marker-color" type="color" value="#4f86f7"></label></div><div id="sn-icon-picker" class="sn-icon-picker" hidden></div><div><strong><?php p($l->t('Live preview')); ?></strong><div id="sn-category-live-preview" class="sn-category-live-preview"><div id="sn-category-live-category">📝 Kategorie</div><h3><?php p($l->t('Example note')); ?></h3><p><?php p($l->t('This is how the final sticky note will look.')); ?></p></div></div></div><label id="sn-cat-system-wrap" hidden class="sn-system-category"><span><input id="sn-cat-system" type="checkbox"> <strong><?php p($l->t('System category')); ?></strong></span><small><?php p($l->t('Visible to all users and editable only by administrators.')); ?></small></label><div class="sn-inline-actions"><button id="sn-cancel-category" type="button"><?php p($l->t('Cancel')); ?></button><button id="sn-save-category" type="button" class="primary"><?php p($l->t('Save category')); ?></button></div></div><div id="sn-categories-list"></div><div class="sn-dialog-actions"><button id="sn-style-close" type="button"><?php p($l->t('Close')); ?></button></div></div></div>
